version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: notifications_db
        MYSQL_PASSWORD: 12345678
        MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
